# global:
#   scrape_interval: 10s
#
# scrape_configs:
#   - job_name: "minecraft"
#     static_configs:
#       - targets: ["minecraft-service:25585"]
#   - job_name: "node_exporter"
#     static_configs:
#       - targets: ["node-exporter:9100"]
