global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "minecraft"
    static_configs:
      - targets: ["mc:25585"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
